### PR TITLE
Unexpected keyword argument 'user_agent'

### PR DESCRIPTION
**Pull request by rsoltys**
Recently, I noticed an issue regarding Subscriber: unexpected keyword argument 'user_agent'. 
Mailerlite API has been changed, so I added new key to Subscriber.

### CODE REVIEW

**Comment by skoudoro** [comment]
Great! Thank you for doing that! I need to find a way / develop a test to check this kind of new parameter.

merging

**Comment by alby-m** [comment]
Thanks for the fix! Do you plan to issue new version that will include this fix any time soon? :pray:

**Comment by skoudoro** [comment]
I would like to add/fix some tests before releasing, so I will try asap @alby-m but I am quite busy this week. Worst case, it should be done by Monday.

**Comment by PhilBeaudoin** [comment]
Thanks for looking into this @skoudoro ! It broke something on my end too. Quite interested by the release! :)

**Comment by skoudoro** [comment]
Ok, many requests so release done (v0.8.0) @PhilBeaudoin, @alby-m, @vitormorales.

Feel free to star the project, it helps 😄!

`pip install -U mailerlite-api-python`

**Comment by skoudoro** [comment]
And thanks all for your feedback!

**Comment by alby-m** [comment]
Thanks a lot, much appreciated :star: @skoudoro

**Pull request merged**
