### PR TITLE
add campaign_name to Activity

### PR DESCRIPTION
**Pull request by rsoltys**

### CODE REVIEW

**Review by skoudoro — COMMENTED** [review]
Hi @rsoltys,

Looks good to me, Thank you for doing this!

Could you also address the pep8 issue above and update the test?

Thank you

**Comment by rsoltys** [comment]
Hi @skoudoro,

I've just resolved issue regarding pep8. I noticed and fixed another issue in Campaign, could you please have a look?
All tests are green in my environment. Hopefully, it is fine now.

Thanks

**Review by skoudoro — APPROVED** [review]
Great! I tested it locally and it is fine for me too.

Thank you again @rsoltys, merging!

**Comment by skoudoro** [comment]
PS: I will cut a release with this change tonight or tomorrow

**Comment by rsoltys** [comment]
Awesome!  Thank you as well.

**Pull request merged**
