### PR TITLE
Unexpected keyword argument 'webform_subscribe_date'

### PR DESCRIPTION
**Pull request by rsoltys**

### CODE REVIEW

**Comment by skoudoro** [comment]
Thanks !

**Comment by rsoltys** [comment]
No problem and thank you as well. Please, do you have any idea how to solve this kind of error in general?

**Comment by skoudoro** [comment]
Not yet, it is quite frustrating. Need to find a workaround to allow the dataclasses to be more flexible. It should be a way to do it. 

I will look into it.

**Comment by skoudoro** [comment]
Also, I just released version 0.10.0 with these fixes

**Comment by skoudoro** [comment]
ok, I might have found a solution using `make_dataclasses`.  e.g: https://stackoverflow.com/a/52536584/17925831

I will try to add that this weekend

**Comment by rsoltys** [comment]
Great news! Thanks

**Pull request merged**
